name: Build

on:
  push:
    branches:
      - '*'
#schedule:
#- cron: "0 2 * * *"

jobs:
  build_and_push:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        target: [x86_64]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"


      - name: Install boto3
        run: python -m pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1


      - name: Get Spack
        uses: actions/checkout@v2
        with:
          path: ./spack
          repository: spack/spack
          ref: develop

      - name: Setup mirror
        run: |
          source spack/share/spack/setup-env.sh
          spack mirror add js947 https://d315ty7cljh88h.cloudfront.net

      - name: Setup keys
        run: |
          echo ${{ secrets.SPACK_KEY }} | base64 -d >spack/var/spack/gpg/fenics.key
          source spack/share/spack/setup-env.sh
          spack gpg init


      - name: Build and push
        run: |
          source spack/share/spack/setup-env.sh
          while read pkg
          do
            spack install $pkg target=${{ matrix.target }}
            spack buildcache create -a --mirror-url ${{ secrets.S3_BUCKET }} $pkg target=${{ matrix.target }}
          done <packages.txt

  reindex:
    needs: build_and_push

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"


      - name: Install boto3
        run: python -m pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1


      - name: Get Spack
        uses: actions/checkout@v2
        with:
          path: ./spack
          repository: spack/spack
          ref: develop

      - name: Update index
        run: |
          source spack/share/spack/setup-env.sh
          spack buildcache update-index --mirror-url ${{ secrets.S3_BUCKET }}
